name: Refresh GitHub Stats

on:
  schedule:
    - cron: "0 6 * * *"  # every day at 6 AM UTC
  workflow_dispatch:      

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping GitHub Readme Stats
        run: |
          curl -s "https://github-readme-stats.vercel.app/api?username=atwalnimrat&show_icons=true&theme=radical" > /dev/null
          curl -s "https://github-readme-streak-stats.herokuapp.com?user=atwalnimrat&theme=dark&hide_border=false" > /dev/null
          curl -s "https://github-readme-stats.vercel.app/api/top-langs/?username=atwalnimrat&layout=compact&theme=tokyonight" > /dev/null
